# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlickrImageList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlickrImageList
    pod 'Alamofire', '~> 5.5'
    pod 'SDWebImage', '5.12.3'
  target 'FlickrImageListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlickrImageListUITests' do
    # Pods for testing
  end

end
